#!/bin/bash
LIBDIR=${HOME}/libs
BCEL_JAR=${LIBDIR}/bcel-5.2.jar
BUILD_DIR=bin
CLASSPATH=${BUILD_DIR}:${BCEL_JAR}
MAX_TIME=0
QUOTA=0;
PORT=4211

java \
  -classpath ${CLASSPATH} \
  hotpotato.acceptance.ServerRunner \
  ${PORT} \
  ${MAX_TIME} \
  ${QUOTA} &

